steps:
- name: 'gcr.io/alert-study-225308/github.com/manishss/devops:c8962f1d6af224fbbc7ee9885abb45bd84d5e7b1'
  args: ['sonar-scanner']
- name: 'gcr.io/cloud-builders/docker'
  args: ["build", "-t", "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}", "."]
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}"]
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - set
  - image
  - 'deployment/devops-1'
  - 'nginx=gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:latest'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_CLOUDSDK_COMPUTE_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLOUDSDK_CONTAINER_CLUSTER}'
