steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ["build", "-t", "gcr.io/${PROJECT-ID}/${IMAGE}", "."]
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/${PROJECT-ID}/${IMAGE}"]
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - set
  - image
  - deployment
  - 'deployment-name=devops-1'
  - 'container=gcr.io/${PROJECT-ID}/${IMAGE}:${COMMIT_SHA}'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_CLOUDSDK_COMPUTE_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLOUDSDK_CONTAINER_CLUSTER}'
