steps:
- name: 'gcr.io/alert-study-225308/github.com/manishss/devops:8f5ffb7b93cefc804501fbd324c63772e6d1d967'
  args: ['sonar-scanner', '-Dsonar.host.url=http://35.232.253.228', '-Dsonar.login=${_LOGIN}', '-Dsonar.password=${_PASS}', '-Dsonar.sources=/workspace']
- name: 'gcr.io/cloud-builders/docker'
  args: ["build", "-t", "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}", "."]
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}"]
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - set
  - image
  - 'deployment/devops-1'
  - 'nginx=gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:latest'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_CLOUDSDK_COMPUTE_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLOUDSDK_CONTAINER_CLUSTER}'
